export const inputSchema = {
  title: 'Connector OS Dutch HNWI Signals Input',
  description: 'Configure AFM signal ingestion and optional Exa confirmation for Apify actor runs.',
  type: 'object',
  schemaVersion: 1,
  properties: {
    runAfmMar19: {
      title: 'Run AFM MAR 19',
      description: 'Ingest the AFM MAR 19 CSV source.',
      type: 'boolean',
      default: true,
    },
    runAfmSubstantialHoldings: {
      title: 'Run AFM substantial holdings',
      description: 'Ingest the AFM substantial holdings CSV source.',
      type: 'boolean',
      default: true,
    },
    runExaConfirmation: {
      title: 'Run Exa confirmation',
      description: 'Enable the optional Exa confirmation pass for shortlisted review records.',
      type: 'boolean',
      default: false,
    },
    afmMar19CsvUrl: {
      title: 'AFM MAR 19 CSV URL',
      description: 'Optional override for the AFM MAR 19 CSV download URL.',
      type: 'string',
      default: '',
    },
    afmSubstantialHoldingsCsvUrl: {
      title: 'AFM substantial holdings CSV URL',
      description: 'Optional override for the AFM substantial holdings CSV download URL.',
      type: 'string',
      default: '',
    },
    lookbackDays: {
      title: 'Lookback days',
      description: 'Number of days used by the scoring pipeline for recency weighting.',
      type: 'integer',
      default: 45,
      minimum: 1,
      maximum: 365,
    },
    minSignalConfidence: {
      title: 'Minimum signal confidence',
      description: 'Confidence threshold used by the existing gating logic.',
      type: 'number',
      default: 0.6,
      minimum: 0,
      maximum: 1,
    },
    minNaturalPersonConfidence: {
      title: 'Minimum natural person confidence',
      description: 'Natural-person threshold used by the existing gating logic.',
      type: 'number',
      default: 0.6,
      minimum: 0,
      maximum: 1,
    },
    maxReviewRecords: {
      title: 'Max review records',
      description: 'Maximum number of review records to export.',
      type: 'integer',
      default: 100,
      minimum: 1,
      maximum: 1000,
    },
    maxMatchReadyRecords: {
      title: 'Max match-ready records',
      description: 'Maximum number of match-ready records to export.',
      type: 'integer',
      default: 30,
      minimum: 1,
      maximum: 500,
    },
    maxShortlistRecords: {
      title: 'Max shortlist records',
      description: 'Maximum number of shortlist-eligible records to export to the shortlist named dataset. The shortlist is a softer gate than match-ready and does not require Exa enrichment.',
      type: 'integer',
      default: 60,
      minimum: 1,
      maximum: 300,
    },
    topBucketBForExa: {
      title: 'Top bucket B for Exa',
      description: 'How many bucket B review records to include in the Exa confirmation shortlist.',
      type: 'integer',
      default: 5,
      minimum: 0,
      maximum: 25,
    },
    exaApiKey: {
      title: 'Exa API key',
      description: 'Optional Exa API key; if blank, the actor falls back to the EXA_API_KEY environment variable.',
      type: 'string',
      default: '',
      isSecret: true,
      editor: 'textfield',
    },
    debug: {
      title: 'Debug logging',
      description: 'Enable verbose debug logging where supported.',
      type: 'boolean',
      default: false,
    },
    runExaEnrichment: {
      title: 'Legacy Exa toggle',
      description: 'Backward-compatible alias for older local runs.',
      type: 'boolean',
      default: false,
    },
    excludeInstitutions: {
      title: 'Exclude institutions',
      description: 'Apply the existing institutional exclusion flag.',
      type: 'boolean',
      default: true,
    },
    exaTopReviewConfirmations: {
      title: 'Legacy Exa shortlist size',
      description: 'Backward-compatible alias for older local runs.',
      type: 'integer',
      default: 5,
      minimum: 0,
      maximum: 25,
    },
    exaFreshnessMaxAgeHours: {
      title: 'Exa freshness max age hours',
      description: 'Maximum age for Exa content fetches.',
      type: 'integer',
      default: 72,
      minimum: 1,
      maximum: 720,
    },
  },
  required: [],
} as const;
