export const inputSchema = {
  title: 'Connector OS Dutch HNWI Signals Input',
  description: 'Configure AFM MAR 19 HTML register scraping and optional Exa confirmation for Apify actor runs.',
  type: 'object',
  schemaVersion: 1,
  properties: {
    dateFrom: {
      title: 'Date from (dd-mm-yyyy)',
      description: 'Start date filter for the AFM MAR 19 register. Leave blank to default to 30 days ago.',
      type: 'string',
      default: '',
    },
    maxPages: {
      title: 'Max pages to scrape',
      description: 'Maximum number of HTML pages to scrape from the AFM register.',
      type: 'integer',
      default: 20,
      minimum: 1,
      maximum: 100,
    },
    runExaConfirmation: {
      title: 'Run Exa confirmation',
      description: 'Enable the optional Exa confirmation pass for shortlisted review records.',
      type: 'boolean',
      default: false,
    },
    minSignalConfidence: {
      title: 'Minimum signal confidence',
      description: 'Confidence threshold used by the existing gating logic.',
      type: 'number',
      default: 0.6,
      minimum: 0,
      maximum: 1,
    },
    minNaturalPersonConfidence: {
      title: 'Minimum natural person confidence',
      description: 'Natural-person threshold used by the existing gating logic.',
      type: 'number',
      default: 0.6,
      minimum: 0,
      maximum: 1,
    },
    minReviewPriorityScore: {
      title: 'Minimum review priority score',
      description: 'Minimum review priority score for shortlist eligibility.',
      type: 'number',
      default: 0.4,
      minimum: 0,
      maximum: 1,
    },
    excludeInstitutions: {
      title: 'Exclude institutions',
      description: 'Apply the existing institutional exclusion flag.',
      type: 'boolean',
      default: true,
    },
    maxReviewRecords: {
      title: 'Max review records',
      description: 'Maximum number of review records to export.',
      type: 'integer',
      default: 100,
      minimum: 1,
      maximum: 1000,
    },
    maxShortlistRecords: {
      title: 'Max shortlist records',
      description: 'Maximum number of shortlist-eligible records to export to the default dataset.',
      type: 'integer',
      default: 60,
      minimum: 1,
      maximum: 300,
    },
    topBucketBForExa: {
      title: 'Top bucket B for Exa',
      description: 'How many bucket B review records to include in the Exa confirmation shortlist.',
      type: 'integer',
      default: 5,
      minimum: 0,
      maximum: 25,
    },
    exaApiKey: {
      title: 'Exa API key',
      description: 'Optional Exa API key; if blank, the actor falls back to the EXA_API_KEY environment variable.',
      type: 'string',
      default: '',
      isSecret: true,
      editor: 'textfield',
    },
    exaFreshnessMaxAgeHours: {
      title: 'Exa freshness max age hours',
      description: 'Maximum age for Exa content fetches.',
      type: 'integer',
      default: 72,
      minimum: 1,
      maximum: 720,
    },
    debug: {
      title: 'Debug logging',
      description: 'Enable verbose debug logging where supported.',
      type: 'boolean',
      default: false,
    },
  },
  required: [],
} as const;
